version: '3.8'

services:
  backend:
    image: anandanlk/communityfl_backend:latest
    container_name: backend_container
    ports:
      - "8088:8088"
    depends_on:
      - mongodb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: anandanlk/communityfl_frontend:latest
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

volumes:
  mongodb_data:
