version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8088:8088"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: